version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back-net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./app/ui
    image: ${USERNAME}/ui:latest
    ports:
      - 9292:9292/tcp
    networks:
      - front-net
  post:
    build: ./app/post-py
    image: ${USERNAME}/post:latest
    networks:
      - back-net
      - front-net
  comment:
    build: ./app/comment
    image: ${USERNAME}/comment:latest
    networks:
      - back-net
      - front-net
volumes:
  post_db:

networks:
  front-net:
  back-net:
          
